spring:
  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usrmng1
    username: root
    password: root
  jpa:     show-sql: true    database-platform: org.hibernate.dialect.MySQL8Dialect    hibernate:      ddl-auto: update
  mail:    host: smtp-mail.outlook.com
    port: 587
    username: akashk33@hotmail.com
    password: SnehalK17123
    properties:      mail:
        smtp:
          auth: true
          starttls:
            enable: true 
    
        
server:  port: 9000      
      
        